### ISSUE TITLE
Archiv

### ISSUE THREAD

**Issue by mmihal** [kodi-czsk/plugin.video.ta3.com#5]
Zdravim,

uz nejaku dobu v plugine TA3 nefunguje prehravanie archivu. Z logu som dostal toto:

```
18:46:02.571 T:1677550576  NOTICE: ["Initializing provider ta3.com with settings {'lang': '0', 'downloads': '', 'quality': '1'}"]
18:46:02.626 T:1397851120   ERROR: EXCEPTION: Window id does not exist
18:46:07.910 T:1677550576   ERROR: Previous line repeats 8 times.
18:46:07.910 T:1677550576  NOTICE: ["Initializing provider ta3.com with settings {'lang': '0', 'downloads': '', 'quality': '1'}"]
18:46:07.939 T:1397851120   ERROR: EXCEPTION: Window id does not exist
18:46:13.055 T:1677550576   ERROR: Previous line repeats 9 times.
18:46:13.055 T:1677550576  NOTICE: ["Initializing provider ta3.com with settings {'lang': '0', 'downloads': '', 'quality': '1'}"]
18:46:13.443 T:1397851120   ERROR: EXCEPTION: Window id does not exist
18:46:14.239 T:1677550576   ERROR: Previous line repeats 1 times.
18:46:14.239 T:1677550576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.ta3.com/default.py", line 40, in <module>
                                                xbmcprovider.XBMCMultiResolverContentProvider(ta3.TA3ContentProvider(tmp_dir=xbmc.translatePath(__addon__.getAddonInfo('profile'))), settings, __addon__).run(params)
                                              File "/home/osmc/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 87, in run
                                                return self.play({'url': params['play'], 'info': params})
                                              File "/home/osmc/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 186, in play
                                                stream = self.resolve(item['url'])
                                              File "/home/osmc/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 346, in resolve
                                                return self.provider.resolve(item, select_cb=select_cb)
                                              File "/home/osmc/.kodi/addons/plugin.video.ta3.com/resources/lib/ta3.py", line 188, in resolve
                                                result = self._resolve_vod(item)
                                              File "/home/osmc/.kodi/addons/plugin.video.ta3.com/resources/lib/ta3.py", line 201, in _resolve_vod
                                                url_format = re.search(r'my.embedurl = \[\{"src" : "([^"]+)"', player_data).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
18:46:14.660 T:1397851120   ERROR: EXCEPTION: Window id does not exist
18:46:14.670 T:1958420480   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ta3.com/?play=68747470733a2f2f7777772e7461332e636f6d2f636c616e6f6b2f313131353333372f686c61766e652d7370726176792d7a2d32382d6f6b746f6272612e68746d6c&cp=7461332e636f6d&]
18:46:15.160 T:1397851120   ERROR: EXCEPTION: Window id does not exist
```
Nema niekto napad ako to fixnut?

**Comment by mx3L** [comment]
opravene v 1.1.4
